import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:2,recordVideo:{dir:'../artifacts/v5-video/raw',size:{width:1920,height:1080}}});await context.addInitScript(()=>{localStorage.setItem('paperWorkshop.onboarding.v1','{"status":"skipped","tourVersion":1}');localStorage.setItem('paperWorkshop.welcome.v1','{"choice":"skip","version":1}');});const page=await context.newPage(),video=page.video(),start=Date.now();
const layout={};async function snap(name,selector){await page.waitForTimeout(700);await page.evaluate(()=>{window.getSelection()?.removeAllRanges();document.activeElement?.blur?.();});const el=selector?page.locator(selector).first():page;await el.screenshot({path:`public/captures/${name}.png`,...(selector?{}:{fullPage:true})});if(selector)layout[name]=await el.boundingBox();console.log(name);}
try{await page.goto('http://127.0.0.1:5194');await page.evaluate(()=>document.fonts.ready);await page.getByTestId('geometry-status').waitFor();await page.waitForTimeout(1500);await snap('overview');await page.getByRole('button',{name:'使用引导',exact:true}).click();await snap('guide-card','.tour-card');await page.keyboard.press('Escape');await page.waitForTimeout(700);
await page.getByRole('button',{name:'留住这一线',exact:true}).click();await page.getByRole('button',{name:'保存当前并开始'}).click();await snap('prediction','.prediction-panel');await page.getByRole('radio',{name:/回到第二刀/}).check();await snap('prediction-selected','.prediction-panel');await page.getByRole('button',{name:'记录预测，展开观察'}).click();await page.waitForTimeout(1100);await snap('status','.diagnosis-panel');
await page.getByRole('button',{name:'新建',exact:true}).click();await page.getByLabel('作品名称').fill('春日 · 第一剪');await page.getByRole('dialog').getByRole('combobox').selectOption('8');await page.getByRole('button',{name:'保存当前并新建'}).click();await page.waitForTimeout(1500);await page.addStyleTag({content:'.folded-canvas {user-select:none;outline:none!important}'});await page.locator('.dual-canvas').scrollIntoViewIfNeeded();await page.waitForTimeout(500);const box=await page.locator('.dual-canvas').boundingBox();const from=(Date.now()-start)/1000;
await page.waitForTimeout(650);const pts=await page.getByTestId('folded-canvas').evaluate(svg=>[[81,14],[60,32]].map(([x,y])=>{const p=new DOMPoint(x,y).matrixTransform(svg.getScreenCTM());return{x:p.x,y:p.y};}));await page.mouse.move(pts[0].x,pts[0].y);await page.mouse.down();for(let i=1;i<=40;i++){await page.mouse.move(pts[0].x+(pts[1].x-pts[0].x)*i/40,pts[0].y+(pts[1].y-pts[0].y)*i/40);await page.waitForTimeout(30);}await page.mouse.up();await page.waitForTimeout(2000);await page.mouse.click(350,80);await page.waitForTimeout(1500);await snap('cut-after','.dual-canvas');const duration=(Date.now()-start)/1000-from;await fs.writeFile('capture-cut.json',JSON.stringify({from,duration,box},null,2));
await page.getByRole('button',{name:'工坊指南',exact:true}).click();await snap('manual','.dialog');await page.getByRole('tab',{name:'动手指南'}).click();await snap('practice','.dialog');await page.getByRole('tab',{name:'我们的团队'}).click();await snap('team','.dialog');
}finally{await fs.writeFile('supplement-layout.json',JSON.stringify(layout,null,2));await context.close();await video.saveAs('../artifacts/v5-video/supplement-raw.webm');await browser.close();}


