import React from 'react';
import {AbsoluteFill,Img,interpolate,useCurrentFrame,Easing,staticFile} from 'remotion';
export const C={paper:'#FFFCF5',base:'#F5EFE3',ink:'#302821',muted:'#6B5748',line:'#C9B79C',red:'#B72D24',teal:'#355B61'};
export const SERIF='Noto Serif SC, SimSun, serif';
export const ease=Easing.bezier(.22,.68,.18,1);
export const p=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{easing:ease,extrapolateLeft:'clamp',extrapolateRight:'clamp'});
export function Paper({children,dark=false}:{children:React.ReactNode;dark?:boolean}){return <AbsoluteFill style={{background:dark?C.red:C.base,color:dark?C.paper:C.ink,fontFamily:'Microsoft YaHei UI, sans-serif',overflow:'hidden',backgroundImage:dark?'none':'radial-gradient(#9C826419 .7px, transparent .7px), radial-gradient(ellipse at 38% 25%, #FFFCF5 0%, transparent 75%)',backgroundSize:'5px 5px, 100% 100%'}}>{children}</AbsoluteFill>}
export function Header({n,label}:{n:number;label:string}){return <><div style={{position:'absolute',left:90,top:56,display:'flex',alignItems:'center',gap:18,color:C.red,fontSize:26,letterSpacing:5}}><span style={{display:'inline-block',width:10,height:10,background:C.red}}/>纸上有数<span style={{color:C.line,fontSize:23}}>／</span><span style={{color:C.muted,fontSize:23,letterSpacing:3}}>{label}</span></div><div style={{position:'absolute',right:90,top:56,fontSize:23,color:C.muted,fontFamily:'Georgia',letterSpacing:3}}>{String(n+1).padStart(2,'0')} / 10</div><div style={{position:'absolute',left:90,right:90,top:105,height:1,background:C.line}}/></>}
export function Title({children,x=110,y=158,size=70,width=1600}:{children:React.ReactNode;x?:number;y?:number;size?:number;width?:number}){const f=useCurrentFrame();const t=p(f,5,34);return <div style={{position:'absolute',left:x,top:y,width,fontFamily:SERIF,fontSize:size,lineHeight:1.4,fontWeight:500,letterSpacing:2,opacity:t,transform:`translateY(${20*(1-t)}px)`}}>{children}</div>}
export function Figure({src,x,y,w,h,style={}}:{src:string;x:number;y:number;w:number;h?:number;style?:React.CSSProperties}){return <Img src={staticFile('captures/'+src+'.png')} style={{position:'absolute',left:x,top:y,width:w,height:h,objectFit:h?'contain':undefined,...style}}/>}
export function Frame({children,x,y,w,h,style={}}:{children:React.ReactNode;x:number;y:number;w:number;h:number;style?:React.CSSProperties}){return <div style={{position:'absolute',left:x,top:y,width:w,height:h,background:C.paper,border:`1px solid ${C.line}`,boxShadow:'0 24px 70px #30282118',overflow:'hidden',...style}}>{children}</div>}
