import { cp, mkdir, writeFile, readFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const {version}=JSON.parse(await readFile('package.json','utf8'));
const destination=resolve(`artifacts/release/纸上有数-v${version}`);
await mkdir(destination,{recursive:true});
for(const item of ['dist-v4','启动第四版.cmd','THIRD_PARTY_NOTICES.md']) await cp(item,resolve(destination,item),{recursive:true});
await mkdir(resolve(destination,'scripts'),{recursive:true});
await cp('scripts/serve.mjs',resolve(destination,'scripts/serve.mjs'));
await mkdir(resolve(destination,'src/audio'),{recursive:true});
await cp('src/audio',resolve(destination,'src/audio'),{recursive:true});
await mkdir(resolve(destination,'src/content'),{recursive:true});
for(const item of ['audio-tracks.ts','local-videos.ts'])await cp('src/content/'+item,resolve(destination,'src/content',item));
await mkdir(resolve(destination,'docs'),{recursive:true});
for(const item of ['manual-validation.md','ai-use-log.md','human-decisions.md','content-sources.md']) await cp(`docs/${item}`,resolve(destination,'docs',item));
await cp('docs/v4-implementation',resolve(destination,'docs/v4-implementation'),{recursive:true});
await mkdir(resolve(destination,'print-samples'),{recursive:true});
for(const item of await readdir('artifacts/print-samples')) if (/\.(html|svg|json)$/.test(item)) await cp(`artifacts/print-samples/${item}`,resolve(destination,'print-samples',item));
await writeFile(resolve(destination,'先读我.txt'),`纸上有数 v${version}\r\n\r\n需要本机已有 Node.js。双击“启动第四版.cmd”，打开 http://127.0.0.1:5192 。\r\n已构建，无需 npm 安装；核心剪纸、课程、音效和打印无需外网。四首本地音乐与五类真人教学片段可离线播放；在线优先尝试 B 站官方播放器。主题与声音在顶栏“设置”中切换。\r\n\r\n不会结束其他服务。不能直接双击 dist-v4/index.html。旧5187/5189/5190存档不共享，请在旧版导出JSON再导入本版。\r\n\r\n具体检查结果见 docs/v4-implementation/README.md，来源见 docs/content-sources.md。\r\n自动化检查不等于真人试用；真机触控、实体打印、实剪、真人学习效果均待验证。\r\n`);
console.log(destination);
